server:
  port: 8769
eureka:
  instance:
    lease-expiration-duration-in-seconds: 1
    lease-renewal-interval-in-seconds: 2
  client:
    serviceUrl:   # Eureka 的服务路径
      defaultZone: http://peer1:8761/eureka/
spring:
  application:
    name: service-hi