server:
  port: 8765
eureka:
  instance:
      lease-expiration-duration-in-seconds: 1
      lease-renewal-interval-in-seconds: 2
  client:
    serviceUrl:   # Eureka 的服务路径
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: service-feign
feign:
  hystrix:
    enabled: true