server:
  port: 8764
eureka:
  instance:
      lease-expiration-duration-in-seconds: 1
      lease-renewal-interval-in-seconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: service-ribbon